# .circleci/config.yml (変更点のみ抜粋)
version: 2.1

jobs:
  # ... (build_and_test, build_production, build_development はそのまま) ...

  deploy_to_github_pages:
    docker:
      - image: cimg/node:20.12.2
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Deploy to GitHub Pages
          command: npm run deploy
      # 環境変数 GITHUB_TOKEN を使用する場合 (推奨):
      # - run:
      #     name: Deploy to GitHub Pages
      #     command: npm run deploy -- --repo=https://${GITHUB_TOKEN}@github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}.git

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build_and_test

      - build_production:
          requires:
            - build_and_test

      - build_development:
          requires:
            - build_and_test

      - deploy_to_github_pages:
          requires:
            - build_production # 本番ビルドが成功したらデプロイ
          filters: # main ブランチへのプッシュでのみデプロイを実行
            branches:
              only:
                - main # あなたのメインブランチ名に合わせる (master の場合もある)